name: Deploy to hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Haciendo deploy
    steps:
      - uses: actions/checkout@master

      - run: rm -rf .github
      - run: echo "This is the Fourth File" > fourthFile.txt && cat fourthFile.txt && pwd
      - run: ls *
      - run: realpath fourthFile.txt

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: gz2jc.ftp.infomaniak.com
          username: gz2jc_docbni
          password: Arches2015$
          port: 22
          source: "./fourthFile.txt"
          target: "/home/clients/a683ce3e7f173dc4178c580ea6b4e7c3/sites/BNIDOC.studio60.ch/Pedro"
