name: Deploy to hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Haciendo deploy
    steps:
      - uses: actions/checkout@v3

      - run: rm -rf .github
      - run: echo "This is the Fourth File" > fourthFile.txt && cat fourthFile.txt && pwd
        shell: bash

      - uses: actions/checkout@master
        name: copy file via ssh password
      - run: pwd && ls -R
        shell: bash
